version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 7
