color: true
reporter: spec
ui: bdd
full-trace: true
exit: true
extension: ['ts', 'js', 'cjs', 'mjs']
require: [
  'ts-node/register'
]
spec: 'test/scripts/**/*.{ts,cjs,mjs}'
watch-files: ['lib/**/*.ts', 'test/**/*.ts']
watch-ignore: ['**/node_modules/**', '**/tmp/**', './dist']
recursive: true