name: Feature request / Improvement
description: I have a feature request, suggestion, improvement etc...
# title: ""
# labels: []
# assignees: []

body:
  - type: checkboxes
    attributes:
      label: Check List
      description: Please check followings before submitting a new feature request.
      options:
        - label: I have already read [Docs page](https://hexo.io/docs/)
        - label: I have already searched existing issues

  - type: textarea
    attributes:
      label: "Feature Request"
      description: "Feature Request description."
      # value:
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Others"
      description: "If you have other information. Please write here."
      # value:
    validations:
      required: false
