'use strict';

describe('Helpers', () => {
  require('./debug');
  require('./css');
  require('./date');
  require('./favicon_tag');
  require('./feed_tag');
  require('./fragment_cache');
  require('./gravatar');
  require('./image_tag');
  require('./is');
  require('./js');
  require('./link_to');
  require('./list_archives');
  require('./list_categories');
  require('./list_posts');
  require('./list_tags');
  require('./mail_to');
  require('./markdown');
  require('./number_format');
  require('./open_graph');
  require('./paginator');
  require('./partial');
  require('./relative_url');
  require('./render');
  require('./search_form');
  require('./tagcloud');
  require('./toc');
  require('./url_for');
});
