version: 1.0
publish: app
services:
  app:
    command:
      - npx hexo server
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 4000
        public: 80