name: Benchmark - Post Process

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

permissions:
  contents: read

jobs:
  profiling-preview:
    if:
      ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event
      == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-slim
    environment:
      name: "profiling-preview"
      url: ${{ steps.get_info.outputs.url }}
      deployment: false
    permissions:
      contents: read
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    env:
      comment_result: "tmp-comment-flamegraph.md"
    steps:
      - uses: actions/download-artifact@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ toJSON( github.event.workflow_run.id ) }}
          pattern: "comment-*"
          merge-multiple: true

      - name: Get PR info
        id: get_info
        run: |
          pr_number=$(cat tmp-comment-pr_number)

          echo "pr_number=$pr_number" | tee -a "$GITHUB_OUTPUT"
          echo "url=https://$pr_number-pr-hexo.surge.sh/" | tee -a "$GITHUB_OUTPUT"

      - name: Publish flamegraph to ${{ steps.get_info.outputs.url }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ steps.get_info.outputs.url }}
          project: ./flamegraph/
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}

      - name: Print full URLs
        if: ${{ steps.get_info.outputs.pr_number!='' }}
        run: |
          echo "## Flamegraph" > ${{ env.comment_result }}
          echo "" >> ${{ env.comment_result }}
          cat tmp-comment-flamegraph-*.md >> ${{ env.comment_result }}

          cat "${{ env.comment_result }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Comment PR - flamegraph
        if: ${{ steps.get_info.outputs.pr_number!='' }}
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.get_info.outputs.pr_number }}
          header: Flamegraph
          path: ${{ env.comment_result }}
