name: Commenter

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  comment-test:
    name: How to test
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request_target'}}
    steps:
      - name: Comment PR - How to test
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          header: How to test
          message: |
            ## How to test

            ```sh
            git clone -b ${{ github.head_ref }} https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
            cd hexo
            npm install
            npm test
            ```
