name: Linter

on:
  push:
    branches:
      - "master"
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/linter.yml"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/linter.yml"

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      - name: Use Node.js 22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #6.4.0
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: |
          npm run eslint
        env:
          CI: true
